pipeline {
    agent any

    environment {
        IMAGE_NAME = "sumitdorugade/cicd-app"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main',
                   url: 'https://github.com/Sumit19D/Docker-Zero-to-Hero.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                cd examples/python-web-app      
                docker build -t $IMAGE_NAME:latest .
                '''
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: '90953881-2dd3-43df-9817-f8efa9bff69b',
                    usernameVariable: 'USER',
                    passwordVariable: 'PASS'
                )]) {
                    sh '''
                    echo $PASS | docker login -u $USER --password-stdin
                    docker push $IMAGE_NAME:latest
                    '''
                }
            }
        }

        stage('Deploy to Kubernetes') {
            environment {
                KUBECONFIG = "/var/lib/jenkins/.kube/config"
            }
            steps {
                sh '''
                cd examples/python-web-app
                kubectl apply -f deployment.yaml --validate=false
                kubectl apply -f service.yaml --validate=false
                '''
            }
        }
    }
}

