pipeline {
    agent any

    environment {
        IMAGE_NAME = "sumitdorugade/cicd-app"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git 'https://github.com/Sumit19D/Docker-Zero-to-Hero.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME:latest .'
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: '9fed644f-67fe-4254-9d19-9b79f5ba7bc1',
                    usernameVariable: 'USER',
                    passwordVariable: 'PASS'
                )]) {
                    sh '''
                    echo $PASS | docker login -u $USER --password-stdin
                    docker push $IMAGE_NAME:latest
                    '''
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh '''
                kubectl apply -f deployment.yaml
                kubectl apply -f service.yaml
                '''
            }
        }
    }
}

